clock: 25
max_err: 3
PDK: sky130
CARAVEL_ROOT: /home/marcus/caravel_rtl_fix/caravel
MCW_ROOT: /home/marcus/caravel_rtl_fix/mgmt_core_wrapper
PDK_ROOT: /home/marcus/caravel_rtl_fix/dependencies/pdks/sky130A
